name: msc-dissertation-eduardo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - pillow
  - pip

  - pip:
    - torch==2.7.1

    - transformers==4.53.2
    - accelerate==1.7.0
    - bitsandbytes==0.46.0
    - datasets==3.6.0
    - sentence-transformers==4.1.0
    - tokenizers==0.21.2
    - safetensors==0.5.3
    - onnx==1.18.0
    - onnxruntime==1.22.0
    - triton==3.3.1
    - faiss-cpu==1.11.0
    
    # LangChain and LlamaIndex
    - langchain==0.3.25
    - langchain-community==0.3.25
    - langchain-core==0.3.65
    - langchain-openai==0.3.24
    - langchain-text-splitters==0.3.8
    - llama-index==0.12.44
    - llama-index-agent-openai==0.4.12
    - llama-index-cli==0.4.3
    - llama-index-core==0.12.44
    - llama-index-embeddings-openai==0.3.1
    - llama-index-indices-managed-llama-cloud==0.7.7
    - llama-index-instrumentation==0.2.0
    - llama-index-llms-openai==0.4.7
    - llama-index-multi-modal-llms-openai==0.5.1
    - llama-index-program-openai==0.3.2
    - llama-index-question-gen-openai==0.3.1
    - llama-index-readers-file==0.4.9
    - llama-index-readers-llama-parse==0.4.0
    - llama-index-workflows==1.0.1
    - llama-cloud==0.1.26
    - llama-cloud-services==0.6.34
    - llama-parse==0.6.34
    
    #RAG
    - ragas==0.1.7
    - colbert-ai==0.2.20
    - chromadb==1.0.12
    - qdrant-client==1.14.2
    - rank-bm25==0.2.2
    
    - fastapi==0.115.9
    - uvicorn==0.34.3
    - flask==3.1.1
    - aiohttp==3.12.11
    - aiosignal==1.3.2
    - anyio==4.9.0
    
    - pylate